"""Audit scoped references and reviewed reverse-direction gaps on saved outputs.

Run after check_house_naming_upgrade.py for preservation of the entire baseline.
The candidate file is the separately retained pre-change metadata comparison,
not expected output generated by the implementation being tested.
"""
import argparse
from collections import Counter, defaultdict
import gzip
import hashlib
import json
from pathlib import Path
import re


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('run', type=Path)
    ap.add_argument('reviewed_candidates', type=Path)
    args = ap.parse_args()
    inputs = [Path(__file__), args.reviewed_candidates, args.run/'summary.json', args.run/'paired-outputs.jsonl.gz']
    hashes = {str(p.resolve()):digest(p) for p in inputs}
    summary = json.loads((args.run/'summary.json').read_text())
    reviewed = {r['filename']:r for r in json.loads(args.reviewed_candidates.read_text())}
    counts = Counter(); by_kind = defaultdict(Counter); examples = defaultdict(list)
    missing = []; ambiguous = []; all_references = []; seen = set()
    with gzip.open(args.run/'paired-outputs.jsonl.gz','rt') as stream:
        for line in stream:
            row=json.loads(line); name=row['filename']; counts['all_inputs']+=1
            assert not row['errors'], row['errors']
            if not row['b']['valid']: continue
            if row['b']['ambiguous']: ambiguous.append(name)
            records=[m['record'] for m in row['b']['matches']]
            for record in records:
                if record['kind'] in {'bill-untyped-numbered','bill-untyped-draft','appropriation-routed'}:
                    # Independent internal captures plus the literal source prefix
                    # catch a numeric token accidentally absorbed into Congress.
                    a_congress={int(f['raw']) for m in row['a']['matches'] for f in m['fields'] if f['name']=='congress'}
                    assert a_congress=={record['congress']}, (name, a_congress, record)
                    assert name.startswith(f"BILLS-{record['congress']}"), name
                    counts['new_layout_congress_checked']+=1
                refs=record.get('references', [])
                if refs: counts['names_with_references']+=1
                for ref in refs:
                    assert ref['sourceField'] in {'subject','descriptionRemainder','description','versionSuffix','voteId','amendmentId','measureList'}
                    value=record[ref['sourceField']]
                    assert 0 <= ref['start'] < ref['end'] <= len(value)
                    assert value[ref['start']:ref['end']] == ref['raw']
                    if ref['type']=='measure' and ref['sourceField'] != 'measureList':
                        assert not re.fullmatch(r'[A-Z][0-9]{6}',ref['raw'],re.I|re.ASCII)
                    counts['reference:'+ref['type']]+=1
                    by_kind[record['kind']][ref['type']]+=1
                    if len(examples[ref['type']]) < 5: examples[ref['type']].append({'filename':name,'record':record})
                if refs: all_references.append({'filename':name,'record':record})
            if name not in reviewed: continue
            seen.add(name)
            available=[ref for record in records for ref in record.get('references',[])]
            for claim in reviewed[name]['claims']:
                fields=claim['fields']; cls=claim['class']
                if cls=='A_print_reference_in_B_suffix':
                    hit=any(r['type']=='rules-committee-print' and r['congress']==int(fields['print_congress']) and r['number']==fields['print_number'] for r in available)
                elif cls=='A_fiscal_year_outside_B_routing_slot':
                    hit=any(r['type']=='fiscal-year' and r['year']==fields['fiscal_year_token'] for r in available)
                else:
                    # Predeclared false-positive counterexample, retained in review.
                    if name=='BILLS-115HR5759ih-HR575921stCentAct.pdf':
                        assert not available
                        counts['ambiguous_ordinal_reference_avoided']+=1
                        continue
                    token=re.sub(r'[^a-z]','',fields['measure_token'].lower())
                    hit=any(r['type']=='measure' and r['measureType']==token and r['measureNumber']==int(fields['measure_number']) for r in available)
                counts[('recovered:' if hit else 'missing:')+cls]+=1
                if not hit: missing.append({'filename':name,'claim':claim,'records':records})
    assert counts['all_inputs']==summary['literal_filenames']
    assert seen==reviewed.keys(), set(reviewed)-seen
    assert all(digest(p)==h for p,h in hashes.items())
    assert all(digest(p)==h for p,h in summary['hashes'].items())
    result={'counts':counts,'by_kind':by_kind,'examples':examples,'missing_reviewed_references':missing,
            'ambiguous_names':ambiguous,'hashes':hashes}
    (args.run/'references-audit.json').write_text(json.dumps(result,indent=2)+'\n')
    with gzip.open(args.run/'references-records.jsonl.gz','wt') as stream:
        for r in all_references: stream.write(json.dumps(r)+'\n')
    print(json.dumps({'counts':counts,'missing_reviewed_references':len(missing),'ambiguous_names':len(ambiguous)},indent=2))
    assert not missing, 'Review references-audit.json'
    assert not ambiguous, 'Review new ambiguity before accepting this corpus run'


if __name__=='__main__': main()
