"""initial schema

Revision ID: 6ca51869ca35
Revises: 
Create Date: 2026-02-01 18:19:46.921954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ca51869ca35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee',
    sa.Column('committee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('committee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chamber', sa.Enum('senate', 'house', name='chamber'), nullable=False),
    sa.PrimaryKeyConstraint('committee_id')
    )
    op.create_table('recording',
    sa.Column('recording_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('youtube', name='recordingtype'), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('recording_id')
    )
    op.create_table('committeemeeting',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('committee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.committee_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('transcript',
    sa.Column('transcript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('automated', 'youtube', 'official', name='transcriptsource'), nullable=False),
    sa.Column('recording_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.recording_id'], ),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript')
    op.drop_table('committeemeeting')
    op.drop_table('recording')
    op.drop_table('committee')
    # ### end Alembic commands ###
