"""Committee meeting transcript models."""

from datetime import datetime
from enum import StrEnum
from typing import TYPE_CHECKING, Optional

from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from committee_meeting.recording import Recording


class TranscriptSource(StrEnum):
    """Origin of a transcript.

    Attributes:
        automated: Generated by automated speech recognition.
        youtube: Provided by YouTube's captioning system.
        official: Official transcript from congressional records.
    """

    automated = "automated"
    youtube = "youtube"
    official = "official"


class Transcript(SQLModel, table=True):
    """A text transcript of a committee meeting recording.

    Attributes:
        transcript_id: Unique identifier for the transcript.
        transcript_url: URL where the transcript can be accessed.
        created_date: Date the transcript was created or obtained.
        source: The origin of the transcript content.
        recording_id: Foreign key reference to the parent recording.
        recording: The recording this transcript was generated from.
    """

    transcript_id: str = Field(primary_key=True)
    transcript_url: str = Field()
    created_date: Optional[datetime] = Field(default=None)
    source: TranscriptSource = Field()
    recording_id: Optional[str] = Field(default=None, foreign_key="recording.recording_id")
    recording: Optional["Recording"] = Relationship(back_populates="transcripts")
